#!/bin/sh
set -e -u -x

echo "Creating Generate OPSMAN USER UAA Client..."
uaac target ${OPSMAN_ENDPOINT}/uaa --skip-ssl-validation
uaac token owner get opsman ${OPSMAN_ADMIN_USER} -s '' -p ${OPSMAN_ADMIN_PASSWORD}
uaac client add ${OPSMAN_CLIENT_ID} \
  --secret ${OPSMAN_CLIENT_SECRET} \
  --authorized_grant_types client_credentials,refresh_token \
  --authorities opsman.admin || true #ignore errors like already exist



  uaac token client get ${OPSMAN_CLIENT_ID} -s ${OPSMAN_CLIENT_SECRET}
